name: rosvm
channels:
  - conda-forge
dependencies:
  - conda-forge::numpy
  - conda-forge::scikit-learn>=0.24
  - conda-forge::pandas
  - conda-forge::scipy
  - conda-forge::joblib
  - conda-forge::cvxpy
  - conda-forge::rdkit
